### ISSUE TITLE
iOS purchase button takes long time to load on Release Product

### ISSUE THREAD

**Issue by aliaftech** [j3k0/cordova-plugin-purchase#1266] opened 2021-11-22 16:29 UTC
### system info

Plugin Version:
  **cordova-plugin-purchase: 10.6.1**

Ionic:
   Ionic CLI                     : 6.18.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.9.1
   @angular-devkit/build-angular : 0.1102.15
   @angular-devkit/schematics    : 11.2.15
   @angular/cli                  : 11.2.15
   @ionic/angular-toolkit        : 3.1.1

Cordova:
   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 34 other plugins)

Utility:
   cordova-res                          : 0.15.3
   native-run (update available: 1.5.0) : 0.2.5

System:
   Android SDK Tools : 26.1.1 (/Users/ali/Library/Android/sdk/)
   ios-deploy        : 1.11.4
   ios-sim           : 8.0.2
   NodeJS            : v16.4.0 (/usr/local/bin/node)
   npm               : 7.18.1
   OS                : macOS Monterey
   Xcode             : Xcode 13.1 Build version 13A1030d

### Expected behavior

Store purchase button should load the product we want to buy right away on Testflight and release environment on iOS

### Observed behavior

I am testing the In App Purchase plugin with ionic and cordova. Our testflight tests work fine and all purchase flow comes up right away, when we press the purchase subscription buttion

but when on the live environment (release version), when we press the purchase subscription button, it takes about 4-5 minutes to load the product.. Once loaded then it works fine and shows right away on second attempt

what I have noticed is that on live environment, when I press store.refresh(), it returns nothing even after waiting for a long time.

I suspect for some reason the refresh() call is not working. 

The flow in which we are doing things on store inti is this, where inAppPurchase2 is the store call:

 1. inAppPurchase2.validator
 2.  inAppPurchase2.when('product').updated
 3. inAppPurchase2.when('product').approved
 4. inAppPurchase2.when('product').verified
 5. inAppPurchase2.when('product').owned
 6. inAppPurchase2.register(product)
 7. inAppPurchase2.refresh()

and then we show the purchase button which basically calls:
inAppPurchase2.order(product.alias)
where we pass the product alias from the product of the store.

Has anyone seen this behaviour before? Right now its very tough to debug and solve the issue when its working fine on testflight and fails/delays on Release env

I suspect its something to do with refresh call, but I may be missing something here.. Its not iOS version dependent.. seen on iOS 14 and 15.

### Steps to reproduce
NA

**Comment by ucsbricks** [comment] 2021-11-24 13:22
Our iOS apps seem to be affected by the same or a similar issue. Dev and TestFlight builds work as expected, but all App Store released builds fail to trigger the system purchase popup. The product has to be in state "valid", otherwise the apps would not have tried to trigger the popup as this condition is checked in their code.

I our case the purchase popup is not delayed on the App Store release by 4 to 5 minutes, but did not show even after 15 minutes plus have passed… Will keep the app in foreground to see, if it appears at some time…

**Comment by j3k0** [comment] 2021-12-13 06:33
Do you have found a reason and solution for this problem?

**Comment by ucsbricks** [comment] 2021-12-15 14:47
@j3k0 so far I could not find a solution. The dialog never showed. But the issue is limited to builds released to the Apple App Store. Therefore debugging is almost impossible. TestFlight and Dev builds work just fine.

**Comment by vasconcelosvcd** [comment] 2021-12-21 16:10
I've got the same issue, the app just instantly closes on production, but with TestFlight and Dev Builds it works just fine

**Comment by aesculus** [comment] 2022-01-16 01:46
Not sure if this is the same as #1279  I get the first popup OK but not the Confirm popup. Works great in V9.0.0 but not V10.3.0 and above.

**Comment by dealervaluations** [comment] 2022-02-02 07:30
Any solution to this? The popup is like taking 1 minute + to appear for me.

**Comment by maxfloden** [comment] 2022-05-16 21:09
I have this problem too, using v 11.0 of plugin. Very hard to debug when woks in debug and testflight but not production. Did anyone find a solution?

**Comment by ucsbricks** [comment] 2022-05-17 08:23
@maxfloden unfortunately I did not find a solution. As I my project schedule was tight when I stumbled across this issue, I had to switch to a different IAP plugin for iOS. I plan to return to cordova-plugin-purchase on iOS if this bug was solved.

**Comment by maxfloden** [comment] 2022-05-21 07:32
@ucsbricks What iap plugin did you use instead?

@j3k0 I have opened an issue with Apple dev support. Will update here if I get more info from them that could help you troubleshoot plugin

**Comment by ucsbricks** [comment] 2022-05-23 08:10
@maxfloden I use a modified version of https://github.com/AlexDisler/cordova-plugin-inapppurchase for iOS. It limits the plugin to iOS only, while a modified Android only version of cordova-plugin-purchase is used as its counterpart. You need to be aware that both plugins’ approaches are quite incompatible, sharing as much of your code as possible might be a bit tricky. The modified plugins I use are hosted in local repos only, as I do not plan to maintain them and get rid of them as soon as possible.

I will keep my fingers crossed, Apple can help. Please share any solution they might come up with. Thanks.

**Comment by j3k0** [comment] 2022-05-23 08:49
Random guesses: maybe this happens because on unwanted calls to refresh? Can you share the code? Some logs with `store.verbosity = store.DEBUG`? (or replace `store` with `inAppPurchase2` on ionic)

**Comment by aliaftech** [comment] 2022-06-15 19:53
https://github.com/j3k0/cordova-plugin-purchase/issues/1248#issuecomment-987963545

Just FYI, this does resolve the issue of delay

**Comment by maxfloden** [comment] 2022-06-18 08:05
> @j3k0 I have opened an issue with Apple dev support. Will update here if I get more info from them that could help you troubleshoot plugin

Just an update to this: I got a final short reply from Apple (after some back and forth, escalation, sending logs etc) that this is a code error. (interesting to me that it it works in Test Flight and passes app review without their tools catching it)

> Engineering confirmed this is not an issue on our end and advised to check or troubleshoot your code.
If you are unsure of how to proceed you can contact our Developer Technical Support team.
The Developer Technical Support team specializes in code-level assistance for Apple frameworks, APIs, and tools.

**Comment by maxfloden** [comment] 2022-06-18 11:02
> Random guesses: maybe this happens because on unwanted calls to refresh? Can you share the code? Some logs with `store.verbosity = store.DEBUG`? (or replace `store` with `inAppPurchase2` on ionic)

@j3k0 Below is excerpt from console log + code. 
When I check/search console log there is only one refresh called.

```
2022-06-18 12:56:35.179073+0200 App[21487:1009359] KeyboardPlugin: resize mode - native
2022-06-18 12:56:35.259922+0200 App[21487:1009359] InAppPurchase[objc] Initialized.
⚡️  Loading app at capacitor://localhost...
To Native Cordova ->  File requestAllPaths File584375289 ["options": []]
⚡️  [log] - onscript loading complete
⚡️  WebView loaded
⚡️  [log] - Hello DataServiceProvider Provider
⚡️  [log] - Hello InAppPurchaseProvider Provider
⚡️  [log] - Hello FirebaseServiceProvider Provider
⚡️  [log] - Angular is running in development mode. Call enableProdMode() to enable production mode.
⚡️  [log] - Ionic Native: deviceready event fired after 227 ms
⚡️  [log] - IAP - function configurePurchasing
⚡️  [log] - IAP - function registerProducts
To Native Cordova ->  InAppPurchase debug InAppPurchase584375290 ["options": []]
To Native Cordova ->  InAppPurchase setup InAppPurchase584375291 ["options": []]
⚡️  [log] - IAP - function itemProductId
⚡️  [log] - IAP - function itemProductId
⚡️  [log] - [store.js] DEBUG: state: mn3_all -> registered
⚡️  [log] - [store.js] DEBUG: ios -> product mn3_all registered
⚡️  [log] - [store.js] DEBUG: state: free -> registered
⚡️  [log] - [store.js] DEBUG: ios -> product free registered
⚡️  [log] - [store.js] DEBUG: state: mn3_theme2 -> registered
⚡️  [log] - [store.js] DEBUG: ios -> product mn3_theme2 registered
⚡️  [log] - [store.js] DEBUG: state: mn3_theme3 -> registered
⚡️  [log] - [store.js] DEBUG: ios -> product mn3_theme3 registered
⚡️  [log] - [store.js] DEBUG: state: mn3_theme4 -> registered
⚡️  [log] - [store.js] DEBUG: ios -> product mn3_theme4 registered
⚡️  [log] - [store.js] DEBUG: state: m2022-06-18 12:56:36.635070+0200 App[21487:1009359] InAppPurchase[objc]: setup: OK
n3_theme5 -> registered
⚡️  [log] - [store.js] DEBUG: ios -> product mn3_theme5 registered
⚡️  [log] - [store.js] DEBUG: state: mn3_theme6 -> registered
⚡️  [log] - [store.js] DEBUG: ios -> product mn3_theme6 registered
⚡️  [log] - [store.js] DEBUG: state: mn3_theme7 -> registered
⚡️  [log] - [store.js] DEBUG: ios -> product mn3_theme7 registered
⚡️  [log] - IAP - function registerHandlers
⚡️  [log] - IAP Refresh Store
⚡️  [log] - [store.js] DEBUG: store.trigger -> triggering action refreshed
⚡️  [log] - [store.js] DEBUG: ios -> initializing storekit
To Native Cordova ->  InAppPurchase load InAppPurchase584375292 ["options": [<__NSArrayM 0x283a1c480>(
mn3_all,
free,
mn3_theme2,
mn3_theme3,
mn3_theme4,
mn3_theme5,
mn3_theme6,
mn3_theme7
)
]]
2022-06-18 12:56:37.105070+0200 App[21487:1009359] InAppPurchase[objc]: load: Getting products data
2022-06-18 12:56:37.105236+0200 App[21487:1009359] InAppPurchase[objc]: load: Set has 8 elements
2022-06-18 12:56:37.105281+0200 App[21487:1009359] InAppPurchase[objc]: load:  - mn3_theme5
2022-06-18 12:56:37.105316+0200 App[21487:1009359] InAppPurchase[objc]: load:  - mn3_theme4
2022-06-18 12:56:37.105346+0200 App[21487:1009359] InAppPurchase[objc]: load:  - mn3_theme3
2022-06-18 12:56:37.105375+0200 App[21487:1009359] InAppPurchase[objc]: load:  - mn3_theme2
2022-06-18 12:56:37.105448+0200 App[21487:1009359] InAppPurchase[objc]: load:  - mn3_all
2022-06-18 12:56:37.105965+0200 App[21487:1009359] InAppPurchase[objc]: load:  - mn3_theme7
2022-06-18 12:56:37.106038+0200 App[21487:1009359] InAppPurchase[objc]: load:  - free
2022-06-18 12:56:37.106068+0200 App[21487:1009359] InAppPurchase[objc]: load:  - mn3_theme6
⚡️  [log] - InAppPurchase[js]: setup ok
⚡️  [log] - [store.js] INFO: ios -> storekit ready
⚡️  [log] - [store.js] DEBUG: ios -> loading products
⚡️  [log] - InAppPurchase[js]: load ["mn3_all","free","mn3_theme2","mn3_theme3","mn3_theme4","mn3_theme5","mn3_theme6","mn3_theme7"]
2022-06-18 12:56:37.109254+0200 App[21487:1009359] InAppPurchase[objc]: load: Starting product request...
2022-06-18 12:56:37.115460+0200 App[21487:1009359] InAppPurchase[objc]: load: Product request started
⚡️  To Native ->  App addListener 107260690
```
  
```
 public configurePurchasing() {
    console.log('IAP - function configurePurchasing');

    if (!this.platform.is('cordova')) { 
      console.log('Not Cordova - IAP not possible'); 
      return false; 
    }

    try {

      this.store.verbosity = this.store.DEBUG;
      this.registerProducts();
      this.registerHandlers();

      this.store.ready(() =>  {
        console.log('IAP Store is Ready');
        // console.log('IAP Products: ' + JSON.stringify(this.store.products));
        // alert('IAP Products: ' + JSON.stringify(this.store.products));

        this.updateItemsWithProductData();  // Update app items with product data
      });

      // Refresh
      console.log('IAP Refresh Store');
      this.store.refresh();

    } catch (err) {
      console.log('IAP - Error On Store Issues: ' + JSON.stringify(err));
    }
  }
```
  
```
  // Register products with store/plugin, all products must be registered
  private registerProducts() {
    try {
      console.log('IAP - function registerProducts');

      // Register full product 
      this.store.register({
        id: this.itemProductId(this.FULLPRODUCT),
        alias: this.itemProductId(this.FULLPRODUCT),
        type: this.store.NON_CONSUMABLE
      });

      // Register each chapter
      let productId;
      let i;
      let items = this.data.allItemsAsArray();
      for (i in items) {
        if (this.platform.is('ios') && items[i].iap_apple_id) {
          productId = items[i].iap_apple_id;
        } else if (this.platform.is('android') && items[i].iap_google_id) {
          productId = items[i].iap_google_id;
        }
    
        if (productId && items[i].parent_id == null) {  // only parent items, not child items
          this.store.register({
            id: productId,
            alias: productId,
            type: this.store.NON_CONSUMABLE
          });
        }
        productId = '';
        
      }

    } catch (err) {
      console.log('IAP Error ' + JSON.stringify(err));
    }
  }
```
  
```
  // Register handlers to listen for store/plugin events
  private registerHandlers() {
    console.log('IAP - function registerHandlers');

    // Handlers
    this.store.when("product").approved( (product: IAPProduct) => {
      console.log('IAP Approved: ' + JSON.stringify(product));
      product.finish();   // Confirm to the store that an approved order has been delivered. This will change the product state from APPROVED to FINISHED + OWNED
    });

    this.store.when("product").owned( (product: IAPProduct) => {  // match any product
      console.log('IAP Owned: ' + JSON.stringify(product));
      this.updateItemsWithProductData();  // Update items 
    });

    this.store.when("product").registered( (product: IAPProduct) => {
      console.log('IAP Registered: ' + JSON.stringify(product));
    });

    this.store.when("product").updated( (product: IAPProduct) => {
      console.log('IAP Updated' + JSON.stringify(product));
    });

    this.store.when("product").cancelled( (product) => {
      console.log('IAP Cancelled' + JSON.stringify(product));
    });

    // Errors
    this.store.when("product").error( (error) => {
      console.log('IAP - An Error Occured: ' + JSON.stringify(error));
      alert('IAP - An Error Occured: ' + JSON.stringify(error));
    });

  }
```
  
```
  // Purchase a product
  public async purchaseProduct(productId: string) {
    console.log('IAP - function purchaseProduct');
    
    if (!this.platform.is('cordova')) { 
      console.log('IAP - not on Cordova, cannot make purchase')
      return; 
    }

    console.log('All store products: ' + JSON.stringify(this.store.products));
    console.log('Ordering From Store: ' + productId);
    try {
      let product = this.store.get(productId);
      console.log('Product info from store: ' + JSON.stringify(product));
      if (product.state === this.store.INVALID) {
        console.log('IAP - Product with id ' + productId + ' is invalid');
      } else {
        // Place product order
        await this.store.order(productId);
        console.log('IAP - Order sent');
      }
    } catch (err) {
      console.log('IAP - Error Ordering ' + JSON.stringify(err));
    }
  }
```

**Comment by maxfloden** [comment] 2022-07-23 23:05
Thanks to Jean-Christophe I got this to work! 
You need to verify before finish on approved event.

```
this.store.when("product").approved( (product: IAPProduct) => {
    // product.finish();
    product.verify().verified((product: IAPProduct) => product.finish());
});
```

**Comment by j3k0** [comment] 2022-07-27 10:45
I believe the more correct solution would be to do:

```js
this.store.when("product")
.approved( (product: IAPProduct) => {
    product.verify();
})
.verified((product: IAPProduct) => {
    product.finish();
});
```

As I think your solution risks creating multiple events handler for the `verified` event.

**Closed** 2022-07-27 10:46 UTC
