### ISSUE TITLE
downloading and downloaded are called twice

### ISSUE THREAD

**Issue by gfragioud** [j3k0/cordova-plugin-purchase#292] opened 2015-09-24 10:37 UTC
function initializeStore() {		
	// Log all errors
    store.error(function(error) {
        customlog(2,'ERROR ' + error.code + ': ' + error.message);
    });
	
	store.register({
		id:    'helloworld', 
		alias: 'helloworld',
		type:   store.NON_CONSUMABLE
	});

	store.when('helloworld').approved(function (product) {
		displayMessage("You've purchased " + product.title + " - it will now download to your device!");
			//hide pricetag and download button, show progress element
			document.getElementById("bpt_"+product.alias).style.display = "none";
			document.getElementById("dimg_"+product.alias).style.display = "none";
			document.getElementById("dp_"+product.alias).style.display = "block";
	});

	// Show progress during hosted content download
	store.when('helloworld').downloading(function(product) {
		customlog(product.alias+" downloading: "+product.progress);
		document.getElementById("dp_"+product.alias).innerHTML = product.progress+'%';
	});

	// When hosted content download is complete, update view and finish the transaction
	store.when('helloworld').downloaded(function(product) {
		customlog(product.alias+" downloaded!");
		
		//refresh view
		updateProduct(product.alias);
		product.finish();
	});

	store.ready(function() {
		customlog("\\o/ STORE READY \\o/");
		var el = document.getElementById('restoreIAP');
                if (el) {
                     el.style.display = 'inline-block';
                     el.onclick = function(ev) {
                         restorePurchases();
                     };
                }
	});

	store.refresh();
}

I have the above function to init my store object.
All seem to be initialized properly and I am able to buy the product, but callbacks "downloading" & "downloaded" are called twice!

I get output something like this:
helloworld downloading: 10%
helloworld downloading: 10%
helloworld downloading: 15%
helloworld downloading: 15%
.
.
.
and finally
helloworld downloaded!
helloworld downloaded!

Any idea why this happens?

**Comment by dpa99c** [comment] 2015-09-24 15:18
I can replicate the duplicate calls to downloading() and have fixed in [this commit](https://github.com/j3k0/cordova-plugin-purchase/commit/592f5eb790a1f1c5e8f8903ec10e24360105f0c9) but can't reproduce duplicate calls to downloaded(). See the log files below which show plugin output before and after the fix in this commit.

**Before**

    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 requested' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download requested' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable requested' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid requested' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'requested' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: ios -> is purchasing uk.co.workingedge.test.inapp.nonconsumablehosted1 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 initiated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download initiated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable initiated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid initiated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'initiated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'updated' (console-via-logger.js, line 173)
    [Log] [store.js] INFO: ios -> transaction 1000000173232409 purchased (1 in the queue for uk.co.workingedge.test.inapp.nonconsumablehosted1) (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 approved' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download approved' (console-via-logger.js, line 173)
    [Log] You've purchased the content for uk.co.workingedge.test.inapp.nonconsumablehosted1 - it will now download to your device! (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable approved' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid approved' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'approved' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'updated' (console-via-logger.js, line 173)
    [Log] [store.js] INFO: ios -> is downloading uk.co.workingedge.test.inapp.nonconsumablehosted1; progress=0%; timeRemaining=-1s (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download downloading' (console-via-logger.js, line 173)
    [Log] Downloaded 0% of uk.co.workingedge.test.inapp.nonconsumablehosted1 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download downloading' (console-via-logger.js, line 173)
    [Log] Downloaded 0% of uk.co.workingedge.test.inapp.nonconsumablehosted1 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'updated' (console-via-logger.js, line 173)
    [Log] [store.js] INFO: ios -> is downloading uk.co.workingedge.test.inapp.nonconsumablehosted1; progress=80%; timeRemaining=-1s (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download downloading' (console-via-logger.js, line 173)
    [Log] Downloaded 80% of uk.co.workingedge.test.inapp.nonconsumablehosted1 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download downloading' (console-via-logger.js, line 173)
    [Log] Downloaded 80% of uk.co.workingedge.test.inapp.nonconsumablehosted1 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'updated' (console-via-logger.js, line 173)
    [Log] [store.js] INFO: ios -> download completed: uk.co.workingedge.test.inapp.nonconsumablehosted1 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 downloaded' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download downloaded' (console-via-logger.js, line 173)
    [Log] Finished downloading uk.co.workingedge.test.inapp.nonconsumablehosted1 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: product -> defer finishing uk.co.workingedge.test.inapp.nonconsumablehosted1 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable downloaded' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid downloaded' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'downloaded' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: product -> finishing uk.co.workingedge.test.inapp.nonconsumablehosted1 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 finished' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download finished' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable finished' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid finished' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'finished' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: ios -> finishing uk.co.workingedge.test.inapp.nonconsumablehosted1 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: ios -> finishing all 1 transactions for uk.co.workingedge.test.inapp.nonconsumablehosted1 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: ios -> finishing 1000000173232409 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 owned' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download owned' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable owned' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid owned' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'owned' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'updated' (console-via-logger.js, line 173)

**After**

    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 requested' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download requested' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable requested' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid requested' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'requested' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: ios -> is purchasing uk.co.workingedge.test.inapp.nonconsumablehosted1 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 initiated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download initiated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable initiated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid initiated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'initiated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'updated' (console-via-logger.js, line 173)
    [Log] [store.js] INFO: ios -> transaction 1000000173232675 purchased (1 in the queue for uk.co.workingedge.test.inapp.nonconsumablehosted1) (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 approved' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download approved' (console-via-logger.js, line 173)
    [Log] You've purchased the content for uk.co.workingedge.test.inapp.nonconsumablehosted1 - it will now download to your device! (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable approved' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid approved' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'approved' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'updated' (console-via-logger.js, line 173)
    [Log] [store.js] INFO: ios -> is downloading uk.co.workingedge.test.inapp.nonconsumablehosted1; progress=0%; timeRemaining=-1s (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download downloading' (console-via-logger.js, line 173)
    [Log] Downloaded 0% of uk.co.workingedge.test.inapp.nonconsumablehosted1 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'updated' (console-via-logger.js, line 173)
    [Log] [store.js] INFO: ios -> is downloading uk.co.workingedge.test.inapp.nonconsumablehosted1; progress=80%; timeRemaining=-1s (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download downloading' (console-via-logger.js, line 173)
    [Log] Downloaded 80% of uk.co.workingedge.test.inapp.nonconsumablehosted1 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'downloading' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'updated' (console-via-logger.js, line 173)
    [Log] [store.js] INFO: ios -> download completed: uk.co.workingedge.test.inapp.nonconsumablehosted1 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 downloaded' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download downloaded' (console-via-logger.js, line 173)
    [Log] Finished downloading uk.co.workingedge.test.inapp.nonconsumablehosted1 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: product -> defer finishing uk.co.workingedge.test.inapp.nonconsumablehosted1 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable downloaded' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid downloaded' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'downloaded' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: product -> finishing uk.co.workingedge.test.inapp.nonconsumablehosted1 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 finished' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download finished' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable finished' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid finished' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'finished' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: ios -> finishing uk.co.workingedge.test.inapp.nonconsumablehosted1 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: ios -> finishing all 1 transactions for uk.co.workingedge.test.inapp.nonconsumablehosted1 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: ios -> finishing 1000000173232675 (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 owned' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download owned' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable owned' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid owned' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'owned' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'uk.co.workingedge.test.inapp.nonconsumablehosted1 updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'hosted content download updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'non consumable updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'valid updated' (console-via-logger.js, line 173)
    [Log] [store.js] DEBUG: store.queries !! 'updated' (console-via-logger.js, line 173)

**Closed** 2015-09-24 15:24 UTC
