### ISSUE TITLE
store.refresh() breaks my App after the first purchase

### ISSUE THREAD

**Issue by ghost** [j3k0/cordova-plugin-purchase#145] opened 2015-03-09 18:01 UTC
I use PhoneGap Build 3.6.3, everything was OK before purchasing the first in-app item. After purchasing the first one, every time the App calls store.refresh() it stops working.
I've already checked #103 and #123 and those are exactly the same problem, but I have no access to "billing_key_param.xml" in PhoneGap Build to work around the problem.

Please help me.

**Comment by tryagains** [comment] 2015-03-12 19:14
Its a problem with the "billing_key_param"
If you cant access billing_key_param.xml then maybe change it in plugin.xml
<config-file target="res/values/billing_key_param.xml" parent="/*">
            <string name="billing_key_param">$BILLING_KEY</string>
</config-file> 
change $BILLING_KEY to your key 

Hopefully fix comes soon

**Comment by carefreews** [comment] 2015-03-14 14:54
@tryagains thank you, but as I said I use Phone Gap Build and I have no access to .xml files you mentioned.

**Comment by tryagains** [comment] 2015-03-14 20:44
you can fork the plugin and install your version after you edit the xml as you have access to the plugins

**Comment by Andrea2985** [comment] 2015-03-14 21:11
hi guys,
I have a problem to retrieve products from the Google store to display them in my app.
can you help me please?

This is my code:

document.addEventListener('onpageshow', onPageShow, false);
		
		

		function onPageShow() {	
			
			store.verbosity = store.DEBUG;
			
			store.register({
			      id: "it.mynewapp.bbm.1l.1as.1es.n2",
			      alias: "Prova",
			      type: store.NON_CONSUMABLE
			    });
			
			store.register({
			      id: "it.mynewapp.prova",
			      alias: "full version",
			      type: store.NON_CONSUMABLE
			    });
			
			      navigator.globalization.getPreferredLanguage(
			    		  function (language) {
			    			var lang=language.value.split("-");	
			    			switch (lang[0]){
			    			case "it":
			    				return;
			    			case "en":
			    			case "es":
			    			case "fr":
			    				i18n.init({ lng: lang[0], debug: true }, function(t) {
				    				  $(".tr").i18n();
				    				  var appName = t("app.name");
				    			});
			    				break;
			    			default:
			    				i18n.init({ lng: "en-US", debug: true }, function(t) {
				    				  $(".tr").i18n();
				    				  var appName = t("app.name");
				    			});	
			    			break;			    			
			    			}
			    					    				 			    				 
			    			},
						    function () {alert('Error getting language\n');}
			      );
			      
			      
			      
			      store.when("product").updated(function (p) {
			          render(p);
			      });
			      
			      store.when("full version").approved(function (order) {
			          order.finish();
			      });
			      
			      store.refresh();
		}
		 
		 function render(product){
			 
			 var elId = product.id;

			    
			    if (!product.loaded) {
			       return;
			    }
			    else if (!product.valid) {
			       $("#L1").append("<li><h3>"+product.title+" non valido</h3></li>");
			    }
			    else if (product.valid) {
			        
			        if (product.canPurchase) {
			        	$("#L1").append("<li><a href='#'><h3>"+product.title+"</h3><p>"+product.description+"</p><p class='ui-li-aside'><strong>"+product.price+"</strong></p></a><a href='#' id="+product.id+" data-icon='gear' data-iconpos='notext'></a></li>");
			        }			        
			        if (product.canPurchase) {
			            $(product.id).onclick = function (event) {
			                var pid = this.getAttribute("id");
			                store.order(pid);
			            };
			        }
			    }
		 }

**Comment by tryagains** [comment] 2015-03-14 21:20
@Andrea2985 check your console or cat log and tell us the error

**Comment by Andrea2985** [comment] 2015-03-14 21:24
it's ok if I run eclipse emulator to get the error?

**Comment by carefreews** [comment] 2015-03-15 17:44
@Andrea2985 Ask your question on StackOverflow.com to get help faster. This thread is for issues with the plugin.

**Comment by Fortuitous** [comment] 2015-04-27 18:29
@carefreews Any luck?  I'm in exactly your boat: PhoneGap Build; crash after first purchase.  Curious as to your progress.  

Did you ever try @tryagains suggestion of forking, editing, (listing your fork on plugins.cordova.io), then calling your plugin from PhoneGap Build?  I've been considering this path, though it seems quite involved and many steps are new to me.  

Is there any news as to whether this has been fixed in the repo but not submitted to plugins.cordova?  Not fixed at all?

I've described this issue in some more detail in #147 .  

Any comments appreciated, thanks.

**Comment by carefreews** [comment] 2015-05-18 01:42
@Fortuitous No, I disappointed using purchase plugin.

**Comment by rob-baker** [comment] 2015-06-10 20:57
has anyone got this plugin working using cordova build?

**Comment by TGNC-dev** [comment] 2015-06-20 06:05
I encounter the same issue using cordova. After the first purchase, my app crashes when i call store.refresh() Here is the error log

E/IABUtil/Security(23761): Base64 decoding failed.
E/AndroidRuntime(23761): FATAL EXCEPTION: Thread-1751
E/AndroidRuntime(23761): Process: com.****.****, PID: 23761
E/AndroidRuntime(23761): java.lang.IllegalArgumentException: com.smartmobilesoftware.util.Base64DecoderException: Bad Base64 input character at 0: 36(decimal)
E/AndroidRuntime(23761): 	at com.smartmobilesoftware.util.Security.generatePublicKey(Security.java:70)
E/AndroidRuntime(23761): 	at com.smartmobilesoftware.util.Security.verifyPurchase(Security.java:47)
E/AndroidRuntime(23761): 	at com.smartmobilesoftware.util.IabHelper.queryPurchases(IabHelper.java:864)
E/AndroidRuntime(23761): 	at com.smartmobilesoftware.util.IabHelper.queryInventory(IabHelper.java:562)
E/AndroidRuntime(23761): 	at com.smartmobilesoftware.util.IabHelper.queryInventory(IabHelper.java:540)
E/AndroidRuntime(23761): 	at com.smartmobilesoftware.util.IabHelper$2.run(IabHelper.java:635)
E/AndroidRuntime(23761): 	at java.lang.Thread.run(Thread.java:848)
E/AndroidRuntime(23761): Caused by: com.smartmobilesoftware.util.Base64DecoderException: Bad Base64 input character at 0: 36(decimal)
E/AndroidRuntime(23761): 	at com.smartmobilesoftware.util.Base64.decode(Base64.java:518)
E/AndroidRuntime(23761): 	at com.smartmobilesoftware.util.Base64.decode(Base64.java:446)
E/AndroidRuntime(23761): 	at com.smartmobilesoftware.util.Base64.decode(Base64.java:392)
E/AndroidRuntime(23761): 	at com.smartmobilesoftware.util.Security.generatePublicKey(Security.java:60)
E/AndroidRuntime(23761): 	... 6 more


Thanks by advance for the help ^^

**Comment by aphil** [comment] 2015-12-10 12:46
@Fortuitous I'm having the same issue, did you have an success forking the plugin? Did you find any way to make it work?

**Closed** 2018-06-10 22:20 UTC
Labels: Backlog, wontfix
