### ISSUE TITLE
Two renewable subscription-products with canPurchase set to false

### ISSUE THREAD

**Issue by solojuve1897** [j3k0/cordova-plugin-purchase#826] opened 2019-04-04 10:14 UTC
So I am implementing auto-renewable subscriptions and have three products: 1 month, 3 months and 6 months. After playing around a bit I placed an order for 6 months and later on I placed an order for 3 months. Now I have two products with the approved state. The validation-service makes two requests on every app-start, one for  each product, containing an identical appStoreReceipt and gets back the same result. Is this correct behaviour? Why I'm asking is because now **both these products have the canPurchase-property set to false**, but actually only one of them should: the last one which was ordered. Because one always should be able to switch between subscriptions.

This testing has happened in the context of iOS.

Any thoughts here?

**Comment by dominic-simplan** [comment] 2019-04-04 13:53
When you have an active 6 month subscription and you order a 3 month subscription, there should be actually a message asking you if you want to switch to the 3 month period subscription after your 6 month subscription has finished.
If you confirm this, you have an active 6 month subscription, and a not yet active 3 month subscription, 
I think you have to wait until the 6 month subscription is finished before you can purchase it again?

**Comment by solojuve1897** [comment] 2019-04-04 14:01
> I think you have to wait until the 6 months subscription is finished before you can purchase it again?

Okey. Possibly so. At the moment I'm sandbox-testing so nothing is active for that long but rather minutes. Yet the two products keep being both **owned** and have the **canPurchase** set to false.

Not all to sure about this.

**Comment by TerryZH** [comment] 2019-04-05 02:09
I had the same problem. The root cause in my case was that the product was in "approved" state, which means a transaction is still in progress. The reason for the in-progress transaction was that my code failed to verify the transaction against the test server (instead, it has been verifying against the production server).

**Comment by j3k0** [comment] 2019-04-05 05:33
On iOS, when switching between subscription levels, the "old" subscription remains active till the end of the period, the "new" subscription will be active right away. So yeah, you might be in this state where a `1 month` subscription will be valid till the end of the month and the `3 month` subscription valid till 3 month + a few days (whatever remains of the 1 month subscription).

Concerning the many requests, the validation logic has this legacy behavior dating from the era where receipts were transaction-specific (this changed with the introduction of `appStoreReceipt`, iOS 7 if I'm correct). I'd definitely like to work on this, but it's an optimisation and I have so much things to do! In production (non-sandbox) people generally don't have more that a dozen transactions to validate anyway. In sandbox, with 5 minutes renewal, this can get quite crazy.

**Comment by albertleao** [comment] 2019-04-07 17:09
@j3k0 Is this the reason for my issues in the other thread?

**Comment by j3k0** [comment] 2019-05-28 09:43
Sorry @albertleao I lag a bit with support requests. Did you figure things out, I think the question on this issue has been answered (so I can close it).

**Closed** 2019-09-25 11:07 UTC
Labels: wontfix
