### ISSUE TITLE
Uncaught TypeError: Object #<Object> has no method 'downloading'

### ISSUE THREAD

**Issue by drago-aca** [j3k0/cordova-plugin-purchase#290] opened 2015-09-23 09:10 UTC
On Android if I use standard command for adding plugin, I get this error.

Uncaught TypeError: Object #<Object> has no method 'downloading'

I think it's old version in NPM, because if I copy github version, everything is OK.

Tnx

**Comment by dpa99c** [comment] 2015-09-23 09:21
I've been looking into this with regard to #281 raised by @G3n3ralTao and I can reproduce this too.

It looks version 3.11.0 was published to npm before the Apple Hosted Content branch was merged. 

Since the version in package.json is 3.11.1, we should bump versions in config.xml and package.json to 3.11.2 and re-publish to npm to resolve this issue - @j3k0 want me to do it?

**Comment by j3k0** [comment] 2015-09-23 09:42
@dpa99c We introduced a few major improvements, including yours and the initial windows support. I bumped version number to 4.0.0 (79449b8) and `npm publish`-ed.

**Comment by drago-aca** [comment] 2015-09-23 09:47
tested..
problem solved..

Thank you, great support and great plugin..

**Closed** 2015-09-23 10:10 UTC
