### ISSUE TITLE
[iOS] store.order() is a NOOP after upgrading to iOS 12

### ISSUE THREAD

**Issue by patrickhulce** [j3k0/cordova-plugin-purchase#787] opened 2018-12-30 20:13 UTC
### system info

```
OSX Mojave 10.14.1
Cordova 8.1.2
Device: iPhone SE iOS 12.1.1
Plugin Version: 7.2.4
```

### Expected behavior
After calling `store.order(<product id>)`, the iOS login/purchase modal popups show to continue the purchase.

### Observed behavior
Nothing happens. 

I receive two product `updated` events with identical payloads after calling `store.order`
```json
{
    "additionalData": null,
    "alias": "monthly subscription",
    "canPurchase": false,
    "countryCode": "US",
    "currency": "USD",
    "description": null,
    "downloaded": false,
    "downloading": false,
    "id": "<product id>",
    "loaded": true,
    "owned": false,
    "price": "$1.99",
    "priceMicros": 1990000,
    "state": "initiated",
    "title": "<product title>",
    "transaction": null,
    "type": "paid subscription",
    "valid": true
}
```

There are no other log statements in XCode after that. 

Looking at the startup logs I see dozens of product purchases queued but nothing happening.

i.e. 20 or so copies of the following 3 lines
```
2018-12-30 13:49:22.395718-0600 My App[355:10976] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <product id>
2018-12-30 13:49:22.395730-0600 My App[355:10976] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 13:49:22.395751-0600 My App[355:10976] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
```

followed by the standard Cordova "resetting plugins" line despite no navigation (see https://stackoverflow.com/questions/27006572/resetting-plugins-due-to-page-load-when-launching-cordova-app-on-iphone) 

```
2018-12-30 14:05:47.023529-0600 My App[263:5326] Resetting plugins due to page load.
2018-12-30 14:05:47.023614-0600 My App[263:5326] InAppPurchase[objc] (before init): WARNING: Your app should be single page to use in-app-purchases. onReset is not supported.
```

Any advice here of possible workarounds would be much appreciated, I'm at my wits end and am about to give up on in app purchases entirely because of this.

### Steps to Reproduce
1. Call `store.order` on a iOS 11 device and finish the purchase.
2. Let it expire.
3. Upgrade to iOS 12
4. Call `store.order` on the now-iOS 12 device.

**Comment by j3k0** [comment] 2018-12-30 21:40
Hi @patrickhulce,

If app startup starts with a load of `paymentQueue:updatedTransactions: <product id>` lines, it means there are transactions in the queue that haven't been finished properly. When this occurs in dev and you need to start fresh, you can use `store.autoFinishTransactions`. Set this to `true` before the initial call to `store.refresh()` and you should (hopefully) be good to go.

> Sometimes during development, the queue of pending transactions fills up on your devices. Before doing anything else you can set `store.autoFinishTransactions` to `true` to clean up the queue. Beware: **this is not meant for production**.

I'm surprised that nothing happens when you call `order()`, I'd expect an error in the log along the lines of _Cannot purchase: there's already a transaction in progress_.

**Comment by patrickhulce** [comment] 2018-12-30 22:01
Thanks for the quick replies!!

> What plugins are you using in your app?

I'm using `file`, `inappbrowser`, `splashscreen`, `screen-orientation`, `whitelist`, `contentsync`, and `x-socialsharing`. What do you think could be racing, are there any in particular you think I should disable?

> When this occurs in dev and you need to start fresh, you can use store.autoFinishTransactions. Set this to true before the initial call to store.refresh() and you should (hopefully) be good to go.

Sorry I forgot to mention, I'm already using this. I've put it in the `deviceready` handler immediately before I register any store listeners/call refresh. Is that the right spot? It doesn't seem to do anything. Is there any log presence I should expect to see that it's doing *something*?

I've attached the full log output of my application startup.

<details>
<summary>Full Logs</summary>

```
2018-12-30 15:55:08.429286-0600 MyApp[364:16455] Apache Cordova native platform version 4.5.5 is starting.
2018-12-30 15:55:08.430099-0600 MyApp[364:16455] Multi-tasking -> Device: YES, App: YES
2018-12-30 15:55:08.434947-0600 MyApp[364:16455] 

Started backup to iCloud! Please be careful.
Your application might be rejected by Apple if you store too much data.
For more information please read "iOS Data Storage Guidelines" at:
https://developer.apple.com/icloud/documentation/data-storage/
To disable web storage backup to iCloud, set the BackupWebStorage preference to "local" in the Cordova config.xml file
2018-12-30 15:55:08.455250-0600 MyApp[364:16455] Using UIWebView
2018-12-30 15:55:08.456926-0600 MyApp[364:16455] [CDVTimer][console] 0.064969ms
2018-12-30 15:55:08.457053-0600 MyApp[364:16455] [CDVTimer][handleopenurl] 0.077009ms
2018-12-30 15:55:08.458453-0600 MyApp[364:16455] [CDVTimer][intentandnavigationfilter] 1.373053ms
2018-12-30 15:55:08.458541-0600 MyApp[364:16455] [CDVTimer][gesturehandler] 0.056028ms
2018-12-30 15:55:08.458652-0600 MyApp[364:16455] [CDVTimer][socialsharing] 0.077963ms
2018-12-30 15:55:08.477613-0600 MyApp[364:16455] [CDVTimer][file] 18.872023ms
2018-12-30 15:55:08.483007-0600 MyApp[364:16455] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2018-12-30 15:55:08.483303-0600 MyApp[364:16455] [MC] Reading from public effective user settings.
2018-12-30 15:55:08.487992-0600 MyApp[364:16455] InAppPurchase[objc] Initialized.
2018-12-30 15:55:08.488034-0600 MyApp[364:16455] [CDVTimer][inapppurchase] 10.347009ms
2018-12-30 15:55:08.532583-0600 MyApp[364:16455] [CDVTimer][splashscreen] 44.510961ms
2018-12-30 15:55:08.532648-0600 MyApp[364:16455] [CDVTimer][TotalPluginStartup] 75.836062ms
2018-12-30 15:55:08.596093-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.596149-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.596164-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.596181-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.596194-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.596205-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.596218-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.598339-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.598420-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.598445-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.598458-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.598469-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.598483-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.598637-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.598652-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.598670-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.598683-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.598694-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.598751-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.598786-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.598798-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.598813-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.598825-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.598836-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.598850-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.598911-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.598925-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.598939-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.598951-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.598962-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.598986-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.599023-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.599073-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.599104-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.599116-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.599127-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.599141-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.599180-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.599192-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.599226-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.599239-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.599250-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.599264-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.599325-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.599363-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.599379-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.599391-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.599429-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.599458-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.599492-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.599503-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.599518-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.599530-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.599541-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.599555-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.599588-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.599619-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.599633-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.599645-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.599657-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.599670-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.599714-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.599726-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.599783-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.599795-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.599806-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.599821-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.599853-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.599866-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.599880-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.599915-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.599926-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.599940-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.599973-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.599985-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.599999-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.600011-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.600023-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.600075-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.600100-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.600132-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.600149-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.600161-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.600172-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.600186-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.600197-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.600248-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.600263-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.600275-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.600286-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.600310-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.600327-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.600360-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.600425-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.600438-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.600449-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.600462-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.600474-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.600507-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.600522-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.600534-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.600569-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.600584-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.600597-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.600629-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.600643-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.600655-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.600666-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.600708-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.600735-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.600768-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.600783-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.600795-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.600806-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.600822-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.600833-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.605796-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.605889-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.605907-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.605920-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.605935-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.605947-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.606009-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.606024-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.606036-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.606047-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.606062-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.606074-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.606108-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.606125-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.606137-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.606148-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.606162-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.606226-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.606264-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.606281-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: <my product id>
2018-12-30 15:55:08.606293-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: Purchasing...
2018-12-30 15:55:08.606304-0600 MyApp[364:16455] InAppPurchase[objc] (before init): paymentQueue:updatedTransactions: State: PaymentTransactionStatePurchasing
2018-12-30 15:55:08.946915-0600 MyApp[364:16455] Resetting plugins due to page load.
2018-12-30 15:55:08.946973-0600 MyApp[364:16455] InAppPurchase[objc] (before init): WARNING: Your app should be single page to use in-app-purchases. onReset is not supported.
2018-12-30 15:55:09.144569-0600 MyApp[364:16455] Received Event:  [object Event]
2018-12-30 15:55:09.144645-0600 MyApp[364:16455] Platform is ios
2018-12-30 15:55:09.144673-0600 MyApp[364:16455] Enable auto finish transactions
2018-12-30 15:55:09.152587-0600 MyApp[364:16455] Refreshing store...
2018-12-30 15:55:09.154785-0600 MyApp[364:16455] InAppPurchase[objc] (before init): setup: OK
2018-12-30 15:55:09.158388-0600 MyApp[364:16455] InAppPurchase[objc] (before init): load: Getting products data
2018-12-30 15:55:09.158442-0600 MyApp[364:16455] InAppPurchase[objc] (before init): load: Set has 1 elements
2018-12-30 15:55:09.158462-0600 MyApp[364:16455] InAppPurchase[objc] (before init): load:  - <my product id>
2018-12-30 15:55:09.158662-0600 MyApp[364:16455] InAppPurchase[objc] (before init): load: Starting product request...
2018-12-30 15:55:09.159135-0600 MyApp[364:16455] InAppPurchase[objc] (before init): load: Product request started
2018-12-30 15:55:09.295326-0600 MyApp[364:16455] Finished load of: file:///var/containers/Bundle/Application/09B46858-8F4D-4CC8-B312-5F472016153D/My%20App.app/www/dist/index.html
2018-12-30 15:55:09.892458-0600 MyApp[364:16455] InAppPurchase[objc] (before init): BatchProductsRequestDelegate.productsRequest:didReceiveResponse:
2018-12-30 15:55:09.892532-0600 MyApp[364:16455] InAppPurchase[objc] (before init): BatchProductsRequestDelegate.productsRequest:didReceiveResponse: Has 1 validProducts
2018-12-30 15:55:09.893097-0600 MyApp[364:16455] InAppPurchase[objc] (before init): BatchProductsRequestDelegate.productsRequest:didReceiveResponse:  - <my product id>: My Subscription Test
2018-12-30 15:55:09.894010-0600 MyApp[364:16455] InAppPurchase[objc] (before init): BatchProductsRequestDelegate.productsRequest:didReceiveResponse: sendPluginResult: (
        (
                {
            countryCode = US;
            currency = USD;
            description = "<null>";
            id = "<my product id>";
            price = "$1.99";
            priceMicros = 1990000;
            title = "My Subscription Test";
        }
    ),
        (
    )
)
2018-12-30 15:55:09.909101-0600 MyApp[364:16455] Received product info [object Object]
2018-12-30 15:55:09.909155-0600 MyApp[364:16455] Received product info [object Object]
2018-12-30 15:55:09.918216-0600 MyApp[364:16455] Received product info [object Object]
```

</details>

**Comment by patrickhulce** [comment] 2018-12-30 22:08
> I'm surprised that nothing happens when you call order(), I'd expect an error in the log along the lines of Cannot purchase: there's already a transaction in progress.

Yeah this is the most frustrating part. It's not clear at all what's going on. The firing of additional product updated events at least gives me confidence that *something* is happening inside the plugin, but I have no idea what.

**Comment by patrickhulce** [comment] 2019-01-06 04:45
@j3k0 @Dexus any other advice you might have?

**Comment by Dexus** [comment] 2019-01-06 18:37
@patrickhulce Sorry, but I am not able to create an example that reproduces this problem. And I also don't have a device I can downgrade/upgrade.

**Comment by patrickhulce** [comment] 2019-01-07 16:20
Thanks for trying @Dexus! I finally gave up and did a factory reset of the phone which fixed the problem. I'm not sure if that makes me feel better though 😅  
 
I mean if this happens to a customer it's not like I'd ask *them* to factory reset 😬

**Comment by Dexus** [comment] 2019-01-07 16:52
Hi @patrickhulce 
A factory reset is really no solution...

Would it be possible for you to provide the source code as a minimal example? Would still try to reproduce it. However, it is very difficult to reproduce every problem, especially since you can't always patch the iOS version up and down on the same device. Feel free to contact me by mail at github@josef-froehle.de 

Any further hint will help to solve the problem.

Regards, Josef

**Comment by patrickhulce** [comment] 2019-01-07 18:01
> Would it be possible for you to provide the source code as a minimal example? Would still try to reproduce it. However, it is very difficult to reproduce every problem, especially since you can't always patch the iOS version up and down on the same device.

I'm afraid not it never seemed to be an issue with the source code, given that it works fine on my factory reset device now without changes 😕My *hope* is that it was just some weird sequence of `purchase -> cancel -> log in -> log out -> upgrade -> ... -> purchase ` during testing that got it into the irrecoverable state and is unlikely to happen to a real user.

**Comment by patrickhulce** [comment] 2019-01-25 15:20
No worries. I don't really have an answer for what happened unfortunately. Things are working now after the factory reset and I haven't been able to replicate the bug.

I suppose this can be closed, but definitely makes me a bit nervous for the first round of iOS updates my users do 😬

**Comment by KleggerKoder** [comment] 2019-02-20 08:30
If it helps anyone else I was having the same problem, turns out I didn't have an "English(U.S.)" localization in the app store information.  Put it in and it came back to life.

**Comment by j3k0** [comment] 2019-02-20 08:36
Thanks @KleggerKoder for the tip.

From both your comments, I guess it's safe to say it was most probably a configuration issue and not something wrong with the plugin. Let's close this then.

**Closed by j3k0** 2019-02-20 08:36 UTC
