### ISSUE TITLE
Promo codes iOS

### ISSUE THREAD

**Issue by rafaellop** [j3k0/cordova-plugin-purchase#530] opened 2016-11-10 15:02 UTC
iOS introduced promotional codes for in-app purchases in October. Does the plugin supports them? I'm asking because I've successfully been using promo codes for IAPs on Android, but on iOS I'm getting empty receipt in my transaction verification script on backend and therefore such transactions are not properly verified. For Android the receipt contains some data, but on iOS the only string that comes as the receipt is 'ios-appstore'. Yes, I mean a string like this. Not a JSON object. I suppose there's something wrong with the validation functions but would be grateful if somebody helps here.

**Comment by j3k0** [comment] 2016-11-12 07:15
I didn't try promo codes on iOS yet. Did you learn anything more about it?

**Comment by rafaellop** [comment] 2016-11-12 09:44
I haven't. I don't know iOS SDK much to find out the reason, but I think the reason is in the plugin which doesn't pass the receipt for promo codes the same way the receipt for normal in app purchases is passed to verification server. What I get on my backend is only the forementioned 'ios-appstore' string. Nothing more. I could take a look if had some clues.

**Comment by stancho-dynoden** [comment] 2017-04-25 14:45
Did you guys get any update on that issue. I have a problem with one of our apps. The promo code is redeemed successfully on the app store but the app does not unlock the in-app purchase. Thanks .

**Comment by shaifd** [comment] 2019-04-04 18:45
Unfortunately it seems that the plugin fails to handle iOS coupons, at least of type Non-Renewing Subscriptions. Coupon is successfully redeemed from the app store. iOS Application that was downloaded from the app store and uses this plugin. Redeem fails. 

Plugin version 7.4.3
Logs show:
\"type\":\"non renewing subscription\"
\"state\":\"approved\"
\"loaded\":true
\"canPurchase\":false
\"owned\":false
\"downloading\":false
\"downloaded\":false
\"additionalData\":null

Also includes valid transaction information

Trying to call store.refresh() again does not help
Tested with multiple iOS devices / users

**Comment by j3k0** [comment] 2019-04-05 05:23
As far as I see, it seems like it works.

`"state":"approved"` means a transaction is approved and in progress, waiting for confirmation from your app that content has been "delivered" and to finish the transaction.

Did you register handlers at app launch?

You should have something like this:

```js
store.when().approved(function (product) {
// store that user is a subscriber on your server or something
product.finish();
});
```

(might be a bit different if you're using a receipt validator)

**Comment by shaifd** [comment] 2019-04-15 19:45
Hi @j3k0 ,
Thanks for your response - I appreciate it. As a short intro I’d like to say that we"re using the purchase plugin for already a couple of years and all in all i works very well with handling IAP (both Android and iOS), thank you for that 😀

As for the problem I mentioned above - our application code have various handlers according to the plugin documentation. Specifically for this item we have handlers for `loaded`, `approved`, `verified` and `error` states.

When we process a normal purchase - it all works well. The problem is with **iOS promo codes** (it works well with any other purchase, both real purchase and Android promo codes). It took us some time to answer as we needed to further investigate it following your response. We found the following:

- We reach the approved handler

- The approved handler calls `product.verify()` which triggers a call to our verify API (with `store.validator`)

- Our server logs show that we get a call for our verification API for this item and that we return from it with `(true, {...transaction details...})` just like it returns for a successful purchase

- Our  app logs show that we did **not** reach the `verified` handler, even though the validator returned a success response

- Our app logs show that we end up in `store.error` function: `store.error(function(e){send some logs});`
The error we get is: `\"code\":6777017,\"message\":\"Transaction verification failed: \"`
As you can see the error message  is empty (no string after _Transaction verification failed:_)

So we fail to understand: why this flow, which works well for regular purchases and passes the validation, does not reach the verified handler and ends with this 6777017 error.

Any idea?

**Comment by shaifd** [comment] 2019-06-30 15:21
Hi @j3k0 , @Dexus,
Any idea if the iOS promo codes issue is going to be addressed in the near future?

**Comment by j3k0** [comment] 2019-09-29 07:34
See #939

**Closed** 2019-09-29 07:34 UTC
