### ISSUE TITLE
[ANDROID] How to test a non-consumable product several times

### ISSUE THREAD

**Issue by francoisduchemin** [j3k0/cordova-plugin-purchase#737] opened 2018-10-12 22:27 UTC
Do you know a way to test the purchase workflow on Android with a consumable product several times?

Let's say I purchase a product. Next time I call `store.refresh()`, `approved()` is automatically called. How can I cancel the purchase? If I go in the Google Play Console and click Refund, the product is marked as _Refunded_ but `approved()` is still called...

With the _cordova-plugin-inapppurchase_ from _AlexDisler_, I could consume the product (even if it was a non-consumable product) and then I could test the purchase workflow again. Is there a way to achieve this with _cordova-plugin-purchase_?

**Comment by j3k0** [comment] 2018-10-13 04:31
A workaround would be to register it as "consumable", then it'll be consumed when you finish the transaction.

**Comment by Dexus** [comment] 2018-10-13 11:36
Normal you should use the “demo Items” provides by the play store for testing. So its your own problem... and you can’t reset if you not have used a test account.

Regards Josef

Von meinem iPhone gesendet

**Comment by francoisduchemin** [comment] 2018-10-13 11:47
Thank you Joseph. With "demo items", you mean _android.test.purchased_, _android.test.canceled_ and _android.test.item_unavailable_, right? I wanted to do a bit more by resetting the purchase so that I can test the whole workflow multiple times. But I guess it's not possible, if I understand correctly.

**Comment by Dexus** [comment] 2018-10-13 12:51
Hi Francois,

The problem is you need to use Test Accounts because it’s not possible to “reset” purchases even if you revert it in the developer console from google. Also you need to reset and clear the app cache. 

It’s not easy to test android and apple purchases. And think about all possible failure points that are coming with it. 

So the easiest way is to have each test round a own test account and cleared caches!

Hope that helps you with your tests.

Regards, Josef

Von meinem iPhone gesendet

**Comment by Dexus** [comment] 2018-10-13 15:46
Hi, I would create one “tester invite” per alias ;) so tester@gmail.com use per round 000001 the alias tester+0000001@gmail.com 

Or create an own “mail domain with a wildcard alias” that accept your invite as beta tester like dates ie 2007-06-05-12-34@aliassub.domain.ltd

Think that would help you at most. 

Von meinem iPhone gesendet

**Comment by francoisduchemin** [comment] 2018-10-13 20:43
Thank you both so much for your answers. Registering the product as _consumable_, and calling `finish()` in the `approved()` function also works fine. It consumes the product, and then the user is forced to buy it again. This is more convenient for me as I don't have to logout/login with different gmail alias users. You can close the issue, everything is working fine.

**Comment by j3k0** [comment] 2018-10-14 17:08
Indeed, since there's no real internal difference on Android between consumable and non-consumable.

But the plugin aims to support both iTunes and Play with a uniform interface. That's why it will never consume a product marked as "non consumable". If I'm correct, for non consumables, `finish()` is almost a `no-operation()` (just setting `owned` to `true`), while for consumable is will call the native `consume()` method.

Thanks for taking time to tell us it's working ;-)

**Closed by j3k0** 2018-10-14 17:08 UTC
